---
jobs:
  - name: renew-certificate
    serial: true
    plan:
      - {trigger: true, get: lets-encrypt-pipeline-src, tags: ['blue-box'], timeout: 2h}
      - task: renew-certificate
        tags: ['blue-box']
        timeout: 2h
        file: lets-encrypt-pipeline-src/tasks/renew-certificate.yml
        params:
          HOSTED_ZONE_ID: ((HOSTED_ZONE_ID))
          AWS_DEFAULT_REGION: ((AWS_DEFAULT_REGION))
          AWS_ACCESS_KEY_ID: ((AWS_ACCESS_KEY_ID))
          AWS_SECRET_ACCESS_KEY: ((AWS_SECRET_ACCESS_KEY))

resources:
  - name: lets-encrypt-pipeline-src
    type: git
    tags: ['blue-box']
    source:
      uri: https://github.com/Kiemes/lets-encrypt-pipeline.git
      branch: master