---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: kiemes/lets-encrypt
inputs:
  - name: lets-encrypt-pipeline-src
  - name: letsencrypt
run:
  path: lets-encrypt-pipeline-src/tasks/print-certificate.sh
params:
  CERTIFICATE_DOMAIN: