---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: 16.04
inputs:
  - name: lets-encrypt-pipeline-src
run:
  path: lets-encrypt-pipeline-src/tasks/renew-certificate.sh
