---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: lets-encrypt-pipeline-src
run:
  path: lets-encrypt-pipeline-src/tasks/renew-certificate.sh
