---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: kiemes/lets-encrypt
inputs:
  - name: lets-encrypt-pipeline-src
outputs:
  - name: letsencrypt
run:
  path: lets-encrypt-pipeline-src/tasks/renew-certificate.sh
params:
  HOSTED_ZONE_ID:
  AWS_DEFAULT_REGION:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  CERTIFICATE_DOMAIN: